const TWITTER_CONSUMER_KEY = '81pA3qsuegJeJXlSm0UVgTIE4';
const TWITTER_CONSUMER_SECRET = 'LxcTrMMGUzAhEfD7yY7PPpDpz3UGyCG28rFJzlzZ5TNGY5Bo6J';
const TWITTER_ACCESS_TOKEN = '2476271131-AwAV6EXQORCyncJjd9dKLupq9qXlyWbYnXclbqb';
const TWITTER_ACCESS_TOKEN_SECRET = 'x7zLKrZjEGCaEUGeUFoF8E7qtlUh7g5dFKVjirUyVyLGv';

export default {
  TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_TOKEN_SECRET,
};